### ISSUE TITLE
Variable load behaves unexpectedly on a current limited source

### ISSUE THREAD

**Issue by calston** [sparkfun/Variable_Load#7]
Connecting the Variable Load to a current limited source yields highly unexpected results.

The load shuts off entirely letting the source recover somewhat and then turns on again, cycling like that without equilibrium

**Comment by mhord** [comment]
This is exactly the behavior I would expect:
1. The supply's current limit is exceeded.
2. The supply voltage folds back.
3. Supply voltage drops below variable load minimum voltage.
4. Variable load shuts off since its minimum voltage check has been violated.
5. No load on supply so supply exits foldback and rebounds.
6. Etc.

**Comment by calston** [comment]
That makes no sense at all. The load is a current device, the voltage from the limited supply drops slightly to maintain constant power. Why on earth would the load shut itself off when the voltage reduces only slightly?

**Comment by calston** [comment]
The virtual resistance of the load should increase proportional to the voltage to maintain a constant load. Instead it shuts off? Did you actually test this before rubbishing my ticket?

**Comment by mhord** [comment]
The new version of firmware will disable the output until a user intervenes when the input dips below Vmin. That will prevent the cycling behavior you've seen.

**Comment by mhord** [comment]
You'll note that I didn't say that the supply "shuts down", I said it "folds back". That means reducing the voltage until the current stabilizes at the limit.

The variable load won't attempt to keep drawing current if the voltage is below 2V. I suspect that if you were to watch the output of your load on a scope you'd see it oscillating above and below 2V as the load kicks on and off. Can you verify this? Again, that's the expected outcome.

The newer version of the code, contributed by keck9939, disables the load once the voltage dips below 2V and doesn't reenable it until the user intervenes. I find this to be a preferable state of affairs.
